<?php
/**
 * ZonemetadataApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Storm\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Storm\PowerDnsClient\Test\Api;

use \Storm\PowerDnsClient\Configuration;
use \Storm\PowerDnsClient\ApiException;
use \Storm\PowerDnsClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ZonemetadataApiTest Class Doc Comment
 *
 * @category Class
 * @package  Storm\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZonemetadataApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createMetadata
     *
     * Creates a set of metadata entries.
     *
     */
    public function testCreateMetadata()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMetadata
     *
     * Delete all items of a single kind of domain metadata..
     *
     */
    public function testDeleteMetadata()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMetadata
     *
     * Get the content of a single kind of domain metadata as a Metadata object..
     *
     */
    public function testGetMetadata()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMetadata
     *
     * Get all the Metadata associated with the zone..
     *
     */
    public function testListMetadata()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifyMetadata
     *
     * Replace the content of a single kind of domain metadata..
     *
     */
    public function testModifyMetadata()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
