<?php
/**
 * ZonesApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Storm\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Storm\PowerDnsClient\Test\Api;

use \Storm\PowerDnsClient\Configuration;
use \Storm\PowerDnsClient\ApiException;
use \Storm\PowerDnsClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ZonesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Storm\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZonesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for axfrExportZone
     *
     * Returns the zone in AXFR format..
     *
     */
    public function testAxfrExportZone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for axfrRetrieveZone
     *
     * Retrieve slave zone from its master..
     *
     */
    public function testAxfrRetrieveZone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createZone
     *
     * Creates a new domain, returns the Zone on creation..
     *
     */
    public function testCreateZone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteZone
     *
     * Deletes this zone, all attached metadata and rrsets..
     *
     */
    public function testDeleteZone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listZone
     *
     * zone managed by a server.
     *
     */
    public function testListZone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listZones
     *
     * List all Zones in a server.
     *
     */
    public function testListZones()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for notifyZone
     *
     * Send a DNS NOTIFY to all slaves..
     *
     */
    public function testNotifyZone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchZone
     *
     * Creates/modifies/deletes RRsets present in the payload and their comments. Returns 204 No Content on success..
     *
     */
    public function testPatchZone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putZone
     *
     * Modifies basic zone data..
     *
     */
    public function testPutZone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rectifyZone
     *
     * Rectify the zone data..
     *
     */
    public function testRectifyZone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
