<?php
/**
 * ZonecryptokeyApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Storm\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Storm\PowerDnsClient\Test\Api;

use \Storm\PowerDnsClient\Configuration;
use \Storm\PowerDnsClient\ApiException;
use \Storm\PowerDnsClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ZonecryptokeyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Storm\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZonecryptokeyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createCryptokey
     *
     * Creates a Cryptokey.
     *
     */
    public function testCreateCryptokey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCryptokey
     *
     * This method deletes a key specified by cryptokey_id..
     *
     */
    public function testDeleteCryptokey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCryptokey
     *
     * Returns all data about the CryptoKey, including the privatekey..
     *
     */
    public function testGetCryptokey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCryptokeys
     *
     * Get all CryptoKeys for a zone, except the privatekey.
     *
     */
    public function testListCryptokeys()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifyCryptokey
     *
     * This method (de)activates a key from zone_name specified by cryptokey_id.
     *
     */
    public function testModifyCryptokey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
